name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Enter project folder
        run: cd ./web
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn eslint "./**/*.{jsx,jsx,ts,tsx}"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Enter project folder
        run: cd ./web
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v18.x
      - name: Install Dependencies
        run: yarn install
      - name: Test - Jest
        run: yarn test
